services:
  db:
    image: pgvector/pgvector:0.8.0-pg17-bookworm
    container_name: pgvector
    environment:
      POSTGRES_USER: embedding
      POSTGRES_PASSWORD: password
      POSTGRES_DB: embedding
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ] # Compose v2, requires NVIDIA Container Toolkit
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull nomic-embed-text &&
      ollama pull gemma3:4b &&
      wait
      "
volumes:
  pgdata:
  ollama-data: